#kubectl apply -f secrets.yml
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-pod-preset-secrets
type: Opaque
#cat ./setup/config/mlab-keys.json | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/ /g' | base64
data:
  nexus-password: X_NEXUS_PASSWORD_X
