apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: jenkins
spec:
  selector:
#    matchLabels:
#      component: jenkins-jenkins-master
#      component: jenkins-jenkins-slave
    matchExpressions:
      - {key: component, operator: In, values: [jenkins-jenkins-master, jenkins-jenkins-slave]}
  env:
    - name: DB_PORT
      value: "6379"
  volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
    - name: cache-volume
      emptyDir: {}
