apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: jenkins-pod-preset-volume-host-home-master
spec:
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [jenkins]}
  env:
    - name: KUBE_ENV
      value: "local"
  volumeMounts:
    - name: host-home
      mountPath: /host-home
  volumes:
    - name: host-home
      hostPath:
        # directory location on host
        path: /host-home
