Persistence:
  Enabled: true
  volumes:
    - name: jekins-host-home
      hostPath:
        path: /host-home
  mounts:
    - name: jekins-host-home
      mountPath: /host-home

Agent:
  Enabled: true
  volumes:
     - type: HostPath
       hostPath: /host-home
       mountPath: /host-home
