kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-host-home
  labels:
    type: local
spec:
  storageClassName: host-home
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/host-home/jenkins/"


