Master:
  Name: jenkins-master
  Image: "kevinstl/jenkins-minikube-easy"
  ImageTag: "0.1.0"
  ImagePullPolicy: "Always"
  UseSecurity: false
  InstallPlugins:
    - kubernetes:1.8.2
    - kubernetes-credentials:0.3.1

  CSRF:
      DefaultCrumbIssuer:
        Enabled: false
  # Kubernetes secret that contains a 'credentials.xml' for Jenkins
  CredentialsXmlSecret: jenkins-credentials
  JavaOpts: >-
    -Djenkins.install.runSetupWizard=false
    -Djava.awt.headless=true
    -Dhudson.model.ParametersAction.keepUndefinedParameters=true
    -XX:+UnlockExperimentalVMOptions
    -XX:+UseCGroupMemoryLimitForHeap
    -XX:+UseParallelGC
    -XX:MinHeapFreeRatio=5
    -XX:MaxHeapFreeRatio=10
    -XX:GCTimeRatio=4
    -XX:AdaptiveSizePolicyWeight=90
  resources:
      requests:
        cpu: "15m"
        memory: "32Mi"
      limits:
        cpu: "500m"
        memory: "128Mi"
  ServiceType: NodePort
  NodePort: 30010



Persistence:
  Enabled: true
  volumes:
    - name: jekins-host-home
      hostPath:
        path: /host-home
    - name: docker-sock
      hostPath:
        path: /var/run
  mounts:
    - name: jekins-host-home
      mountPath: /host-home
    - name: docker-sock
      mountPath: /var/run


Agent:
  Enabled: true
  Image: "kevinstl/jenkins-agent-minikube-easy"
  ImageTag: "0.1.0"
  AlwaysPullImage: false
  volumes:
     - type: HostPath
       hostPath: /host-home
       mountPath: /host-home
     - type: HostPath
       hostPath: /var/run
       mountPath: /var/run
  Cpu: 2000m
  Memory: 3072Mi
  JavaOpts: >-
    -Djenkins.install.runSetupWizard=false
    -Djava.awt.headless=true
    -Dhudson.model.ParametersAction.keepUndefinedParameters=true
    -XX:+UnlockExperimentalVMOptions
    -XX:+UseCGroupMemoryLimitForHeap
    -XX:+UseParallelGC
    -XX:MinHeapFreeRatio=5
    -XX:MaxHeapFreeRatio=10
    -XX:GCTimeRatio=4
    -XX:AdaptiveSizePolicyWeight=90
#  resources:
#      requests:
#        cpu: "15m"
#        memory: "32Mi"
#      limits:
#        cpu: "500m"
#        memory: "128Mi"



  PodTemplates:

    Nodejs:

      Enabled: true
      NodeSelector: {}

      volumes:
         - type: HostPath
           hostPath: /host-home
           mountPath: /host-home
         - type: HostPath
           hostPath: /var/run
           mountPath: /var/run

      Cpu: 2000m
      Memory: 3072Mi

      Privileged: false

      Name: nodejs
      # ServiceAccount: fooo
      Label: jenkins-nodejs
      volumes:
      - type: Secret
        secretName: jenkins-docker-cfg
        mountPath: /home/jenkins/.docker
      EnvVars:
        JENKINS_URL: http://jenkins:8080
        GIT_COMMITTER_EMAIL: jenkins-x@googlegroups.com
        GIT_AUTHOR_EMAIL: jenkins-x@googlegroups.com
        GIT_AUTHOR_NAME: jenkins-x-bot
        GIT_COMMITTER_NAME: jenkins-x-bot
        XDG_CONFIG_HOME: /home/jenkins
        DOCKER_CONFIG: /home/jenkins/.docker/
      ServiceAccount: jenkins
      Containers:
        Jnlp:
          Image: kevinstl/jenkins-agent-minikube-easy:0.1.0
          RequestCpu: "100m"
          RequestMemory: "128Mi"
          Args: '${computer.jnlpmac} ${computer.name}'
        Nodejs:
          Image: jenkinsxio/builder-nodejs:0.0.317
          Privileged: true
          RequestCpu: "400m"
          RequestMemory: "512Mi"
          LimitCpu: "2000m"
          LimitMemory: "2048Mi"
          # You may want to change this to true while testing a new image
          # AlwaysPullImage: true
          Command: "/bin/sh -c"
          Args: "cat"
          Tty: true





rbac:
  install: true

